spring:
  application:
    name: asa-api
  jackson:
    default-property-inclusion: NON_NULL
  mail:
    username: alvarezcesar.84@gmail.com
    host: smtp.gmail.com
    password: iqpabanguckhllny
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
            required: true
  
server:
  port: 25000
  servlet:
    context-path: /ASAApi
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  ssl:
    key-store-type: PKCS12
    key-store: classpath:baeldung.p12
    key-store-password: JvhAsa2020*
    key-alias: tomcat
    enabled: false
      
#asa:
#  jwt:
#    expiration: 60000000
