spring:
  application:
    name: asa-service
  jackson:
    default-property-inclusion: NON_NULL 
    
server:
  port: 25001
  servlet:
    context-path: /ASAService
    encoding:
      enabled: true
      charset: UTF-8
      force: true