spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    password: Abc123*
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ASA_DEMO
asa:
  jwt:
    expiration: 600000000
    secret: Abc1234*
  server:
    sbo: http://localhost:25002/ASASbo/
  report: 
    path: C:/Program Files/Apache Software Foundation/Tomcat 9.0/webapps/ASA_Files/Jasper