spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    password: Abc123*
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ASA_DEMO